fix some words
ytknzw/covid19_fastai_translation pull request #2
Opened 2020-03-16 09:19 UTC by Hiroki-Mori360

2020-03-16 13:01 UTC, ytknzw requested changes
Reviewed.

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +>私たちはデータサイエンティストである — それはつまり、私たちの仕事はデータを分析し解釈する方法を理解することです。私たちは新型コロナ、COVID-19に関するデータを分析し、その結果を非常に懸念しています。高齢者や貧困層といった社会の最も脆い部分が最も危険にさらされていますが、この疾病の広がりと影響をコントロールするには私たち*全員*が行動を変えることが必要です。しっかりと繰り返し手を洗い、
```suggestion
>私たちはデータサイエンティストである — それはつまり、私たちの仕事はデータを分析し解釈する方法を理解することです。私たちは新型コロナ、COVID-19に関するデータを分析し、その結果を非常に懸念しています。高齢者や貧困層といった社会の最も脆い部分が最も危険にさらされていますが、この疾病の広がりと影響をコントロールするには私たち*全員*が行動を変えることが必要です。しっかりと繰り返し手を洗い、集団や人混みを避け、イベントをキャンセルし、そして顔を触らないようにしないといけません。この投稿では、私たちが懸念している理由と、あなたもそうすべき理由を説明します。あなたが知るべき重要な情報を非常によくまとめたものとして、イーサン・アレイ（パンデミックによるリクスを低減させる技術を開発しているNPOの代表）による[『新型コロナの概要』](https://docs.google.com/document/u/1/d/1vumYWoiV7NlVoc27rMQvmVkVu5cOAbnaW_RKkq2RMaQ/mobilebasic?fbclid=IwAR0If1zzDDldgAy3DZmFhaxAmP046-dwAE_LCj3l9su2XLYpZe2By8mCj1A)を読んで下さい。
```

- Accepted: 顔を触らないようにしないといけません。

- > For an excellent summary of the key information you need to know,
    - 「あなたが知るべき重要な情報を非常によくまとめたものとして、」はいかがでしょう？

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +平均して、インフルエンザに感染している人は、他の1.3人に感染させます。それがインフルエンザの「R0」と呼ばれる値です。もしR0が1.0未満なら、感染は拡大が止まり終息します。もしそれが1.0超なら、感染が拡大します。中国以外におけるCOVID-19のR0は現在2から3です。差は小さいように聞こえますが、20'世代'にわたり感染者が他の人を感染させた後を比較すると、R0が1.3なら感染者数は14
```suggestion
平均して、インフルエンザに感染している人は、他の1.3人に感染させます。それがインフルエンザの「R0」と呼ばれる値です。もしR0が1.0未満なら、感染は拡大が止まり終息します。もしそれが1.0超なら、感染が拡大します。中国以外におけるCOVID-19のR0は現在2から3です。差は小さいように聞こえますが、20“世代”にわたり感染者が他の人を感染させていった後では、R0が1.3なら感染者数は146人ですが、R0が2.5なら3600万人に達し得ます！（これは、もちろん、大雑把なもので現実世界の影響を無視しています。しかし、他の条件が同じだとした場合のCOVID-19とインフルエンザとの*相対的な*違いの合理的な説明です。）
```
* > '世代'
    - 強調記号の使い方を調べたところ、“”または『』が適切なようです。
* > 感染させた後を比較すると
    - 原文に「比較する」という表現はなく、直前に「差は小さいように聞こえますが」という比較に関する表現があるので、ここでは訳出しないでおきます。また、この訳だと"passing on"が落ちてしまいます。

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +R0は疾病の基本的特性ではないということに注意して下さい。R0は疾病への対応に大きく左右されますし、時間とともに変化する可能性があります[^2]。最も特筆すべきことに、中国におけるCOVID-19のR0は大幅に低下していて、今や1.0に近づいています！どうやって？と疑問になるでしょう。アメリカのような国においては想像しがたい規模で対策を講ずることによってです。例えば、多くの大都市を完全に閉鎖する
Accepted.

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +他に、あなたの地域におけるCOVID-19の影響を直感的に理解するのを難しくしているのは、感染と入院との間に非常に大きな時間差があることです — 大まかには約11日です。これは長い期間だとは思わないかも知れません。しかし、その期間に感染する人々の数に例えると、病院のベッドが満員だと気づく頃には既に処置が必要な人が5〜10倍いるレベルで地域の感染が拡大していることを意味します。
Accepted.

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +しかし、「落ち着け」は準備と対応の失敗へと容易につながります。今のアメリカの統計値に中国が達した時点では、中国では何千万人もの人々が封鎖状態に置かれて新たに2つの病院が建設されました。イタリアは長く待ち過ぎて、1600万人を封鎖状態に置いたにも関わらず、ちょうど今日（3月8日日曜日）1492人の感染と133人の死亡を新たに発表しました。現段階で私たちが確かめられる最も正確な情報に基づくと、たった
Accepted.

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +そしてもちろん、あなたのすぐそばにいる人々だけの問題ではありません。これは非常に重要な倫理的論点です。1人1人がこのウィルスの拡散をコントロールすることにできるだけ貢献することが、社会全体が感染率を鈍化させるのに役立ちます。ゼネップ・テュフェクチが[サイエンティフィック・アメリカンに寄稿した](https://blogs.scientificamerican.com/observations/p
Accepted.

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +しかし、それが正しいことだと分かっていました。なぜなら、そうしなければ私たちの地域でこの病気の拡大を私たちが大きくしてしまう可能性があるからです[^4]。
```suggestion
しかし、それが正しいことだと分かっていました。なぜなら、そうしなければ私たちの地域でこの病気の拡散を私たちが大きくしてしまう可能性があるからです[^4]。
```
「拡大を大きくする」は冗語なので、「拡散を大きくする」はいかがでしょうか？

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +これは大変に重要なことです。なぜなら、もし地域における感染率を鈍化させられれば、そこの病院は感染者と普段から治療すべき通院患者の両方を処置する時間を与えられるからです。その鈍化は「曲線を低くすること」というように言い表されますが、それはこのイメージ図を見れば明らかです：
```suggestion
これは大変に重要なことです。なぜなら、もし地域における感染率を鈍化させられれば、感染者と、もともと治療しなければならない一定数の患者の両方に対処する時間をそこの病院に与えることができるからです。その鈍化は「曲線を低くすること」というように言い表されますが、それはこのイメージ図を見れば明らかです：
```
以下を踏まえて訳を変更しました。
* > we give hospitals in that community time to deal with
    * 「与えられる」は受け身ではなく可能の意味で訳しました。
* > the regular patient load
    * 通院患者というある特定の患者の一群ではなく、"load"が表すように不特定の患者により日常的に発生している治療への需要を指していると思います。

2020-03-16 13:01 UTC, ytknzw commented on Covid-19, your community, and you — a data science perspective JP.md
> +>高齢者と障害者の日常生活や支援システムが破壊されると、彼らは際立った危険にさらされます。地方あるいはネイティヴアメリカンの居留地を含む、たやすく医療へアクセスできない人々は必要な時に恐ろしいギャップに直面するかも知れません。狭苦しい場所 — 公共住宅、介護施設、刑務所、シェルターまたは通りのホームレスさえも — に住む人々は感染の波に苦しむかも知れません。これは既にワシントン州で見られています
Accepted.

2020-03-17 01:07 UTC, Hiroki-Mori360 commented on Covid-19, your community, and you — a data science perspective JP.md
> +>私たちはデータサイエンティストである — それはつまり、私たちの仕事はデータを分析し解釈する方法を理解することです。私たちは新型コロナ、COVID-19に関するデータを分析し、その結果を非常に懸念しています。高齢者や貧困層といった社会の最も脆い部分が最も危険にさらされていますが、この疾病の広がりと影響をコントロールするには私たち*全員*が行動を変えることが必要です。しっかりと繰り返し手を洗い、
```suggestion
>私たちはデータサイエンティストである — それはつまり、私たちの仕事はデータを分析し解釈する方法を理解することです。私たちは新型コロナ、COVID-19に関するデータを分析し、その結果を非常に懸念しています。高齢者や貧困層といった社会の最も脆い部分が最も危険にさらされていますが、この疾病の広がりと影響をコントロールするには私たち*全員*が行動を変えることが必要です。しっかりと繰り返し手を洗い、集団や人混みを避け、イベントをキャンセルし、そして顔を触らないようにしないといけません。この投稿では、私たちが懸念している理由と、あなたもそうすべき理由を説明します。あなたが知るべき重要な情報を非常によくまとめたものとして、イーサン・アレイ（パンデミックによるリスクを低減させる技術を開発しているNPOの代表）による[『新型コロナの概要』](https://docs.google.com/document/u/1/d/1vumYWoiV7NlVoc27rMQvmVkVu5cOAbnaW_RKkq2RMaQ/mobilebasic?fbclid=IwAR0If1zzDDldgAy3DZmFhaxAmP046-dwAE_LCj3l9su2XLYpZe2By8mCj1A)を読んで下さい。
```

2020-03-17 01:07 UTC, Hiroki-Mori360 commented on Covid-19, your community, and you — a data science perspective JP.md
> +>私たちはデータサイエンティストである — それはつまり、私たちの仕事はデータを分析し解釈する方法を理解することです。私たちは新型コロナ、COVID-19に関するデータを分析し、その結果を非常に懸念しています。高齢者や貧困層といった社会の最も脆い部分が最も危険にさらされていますが、この疾病の広がりと影響をコントロールするには私たち*全員*が行動を変えることが必要です。しっかりと繰り返し手を洗い、
> イーサン・アレイ（パンデミックによるリクスを低減させる技術を開発しているNPOの代表）

リクス -> リスク

2020-03-17 01:46 UTC, merged